apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: simple-go
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - overlay: eks
        appBranch: main
      - overlay: gke
        appBranch: main
  template:
    metadata:
      name: 'simple-go-{{overlay}}'
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            maxDuration: 3m0s
            factor: 2
      source:
        repoURL: https://github.com/christianh814/simple-go
        targetRevision: '{{appBranch}}'
        path: 'deploy/overlays/{{overlay}}'
      destination:
        name: '{{overlay}}-cluster'
        namespace: 'simple-go-{{overlay}}'
